import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Code} from '@chakra-ui/react'

export default function About() {
    return (
      <div className={styles.container}>
        
        <Head>
          <title>Contact</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        
        
        <main className={styles.main}>       
          <h1 className={styles.title}>
            <a href="https://www.instagram.com/j_damusicophile/">About Me</a>
          </h1>
         </main> 
        </div>
    )
}