import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Text, Button} from '@chakra-ui/react'
import {WarningTwoIcon, PhoneIcon} from '@chakra-ui/icons'
import NextLink from 'next/link';


export default function Home() {
   return (
    <div className={styles.container} >
     <background/>
      <Head>
        <title>Josh Silva | Ops</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Josh_Logo_White.png" />
        <script data-ad-client="ca-pub-1604087287433448" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
      </Head>
      
      
      <main className={styles.main}>    
        <h1 className={styles.title}>
          <a href="https://www.instagram.com/j_damusicophile/" fontWeight="extrabold">Sorry Guys!</a>
        </h1>
        
        <br/>
        <br/>
        <Text className={styles.description} fontWeight='thin'>
            <WarningTwoIcon/> &nbsp; This page is currently under construction to bring you the best experieince. So Please hang on tight. If it is urgent or have any suggestions don't hesitate to contact me via avaiable social medial platforms in this link.
            <br/>
                <Button as="a" variant="ghost" aria-label="Home" href="/Contact" passHref>
                    <PhoneIcon/> &nbsp;
                  Contact me
                </Button>
            
        </Text>
      </main>    
      
    </div>
  )
}
