import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Code, IconButton} from '@chakra-ui/react'


export default function Contact() {
    return (
      <div className={styles.container}>
        
        <Head>
          <title>Josh Silva | Contact</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Josh_Logo_White.png" />
        </Head>
        
        
        <main className={styles.main}>       
          <h1 className={styles.title}>
            <a>Contact Me</a>
          </h1>

          <h2>Please follow me on social media!</h2>

          <div className={styles.grid}>
          <a href="https://www.instagram.com/j_damusicophile/" className={styles.card}>
            <h2>Instagram &rarr;</h2>
            <p></p>
          </a>

          <a href="https://twitter.com/JDaMusicophile" className={styles.card}>
            <h2>Twitter &rarr;</h2>
            <p></p>
          </a>

          <a
            href="https://www.facebook.com/JDaMusicophile"
            className={styles.card}
          >
            <h2>Facebook &rarr;</h2>
            <p></p>
          </a>

          <a
            className={styles.card}
          >
            <h2>Discord &rarr;</h2>
            <p>JDaMusicophile#0630</p>
          </a>

          
        </div>
        </main>
      </div>
    )
}