import React from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import { Divider, Text, Box, useDisclosure, Modal,
  ModalOverlay,
  ModalContent,
  ModalHeader,
  ModalFooter,
  ModalBody,
  ModalCloseButton,} from '@chakra-ui/react'
import ReactTypingEffect from 'react-typing-effect'
import { motion } from 'framer-motion'



export default function Home() {
  
   return (
    <div className={styles.container} >
      <Head>
        <title>Josh Silva | A Dog's Guide</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Josh_Logo_White.png" />
        <script data-ad-client="ca-pub-1604087287433448" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <meta name="google-site-verification" content="AJMl2Noy2tSRNUBlK3Fcmcqayv3lwjELM20KbLxAhIQ" />
      </Head>
      
      
      <main className={styles.main}>   
      <motion.div
  animate={{
    x: 0,
    y: 0,
    scale: 0.4,
    rotate: 360,
  }}
>  
<img src="https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/160/apple/81/dog-face_1f436.png" width="200" height="200"/>
</motion.div>
        <h1 className={styles.title}>            
            <a>A Dog's Guide</a>       
        </h1>

        <br/>
        
        <Text className={styles.description} fontWeight='thin' fontFamily="serif">
          Welcome to the Ultimate Dog Guide
        </Text>
        <br/>
        <Box padding='10' maxW="sm" borderWidth="1px" borderRadius="lg" overflow="hidden" className={styles.glass}>
          <Box mt="1"
          fontWeight="semibold"
          as="h4"
          lineHeight="tight"
          >
            <p > <img src="https://raw.githubusercontent.com/MartinHeinz/MartinHeinz/master/wave.gif" width="30px" height="20px"/>Hi I'm Josh</p>
            <Text fontWeight="thin">A Dog Lover, Owner and a Noob at training a Dog 😅.<br/> However, I have experience in bringing up my own canine friend and living happily!</Text>
          </Box>
        </Box>

        <br/>
        <br/>
        <br/>
        <br/>        

        <Divider />

        <main>       
          <div className={styles.grid}>
          <a className={styles.card} onClick= {SizeExample}>
            <h2>Step 1: Why Get a Dog? &rarr;</h2>
            <p></p>
          </a>

          <a href="" className={styles.card}>
            <h2>SpaceX Launches &rarr;</h2>
            <p></p>
          </a>

          <a
            href=""
            className={styles.card}
          >
            <h2>Astronomy &rarr;</h2>
            <p></p>
          </a>

          <a
            href="/Web_Development"
            className={styles.card}
          >
            <h2>Web Development &rarr;</h2>
            <p></p>
          </a>

          <a href="/dog" className={styles.card}>
            <h2>A Dog's Guide &rarr;</h2>
            <Text fontWeight='thin' fontSize='small' fontStyle='normal'> Do you want to or already own a dog? Click this guide to find out more </Text>
          </a>
        </div>
        </main>
        

        <br/>
        
        
      </main> 
       
      
      
    </div>
  )
}

function SizeExample() {
  const { isOpen, onOpen, onClose } = useDisclosure()
  const [size, setSize] = React.useState("md")

  const handleSizeClick = (newSize) => {
    setSize(newSize)
    onOpen()
  }

  const sizes = ["xs", "sm", "md", "lg", "xl", "full"]

  return (

      <Modal onClose={onClose} size={size} isOpen={isOpen}>
        <ModalOverlay />
        <ModalContent>
          <ModalHeader>Modal Title</ModalHeader>
          <ModalCloseButton />
          <ModalBody>
            <p>Hi</p>
          </ModalBody>
          <ModalFooter>
            <Button onClick={onClose}>Close</Button>
          </ModalFooter>
        </ModalContent>
      </Modal>
    
  )
}