import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Code} from '@chakra-ui/react'

export default function Home() {
   return (
    <div className={styles.container} >
      
      <Head>
        <title>Josh Silva</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Josh_Logo_White.png" />
        <script data-ad-client="ca-pub-1604087287433448" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
      </Head>
      
      
      <main className={styles.main}>    
        <h1 className={styles.title}>
          <a href="https://www.instagram.com/j_damusicophile/" >Josh Silva</a>
        </h1>
        
        <p className={styles.description}>
          Welcome to my {' '}
          <Code className={styles.code}>Personal Portfolio</Code>
        </p>
      </main>
    </div>
  )
}
