import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import { Text } from '@chakra-ui/react'


export default function About() {
    return (
      <div className={styles.container}>
        
        <Head>
          <title>Josh Silva | More</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Josh_Logo_White.png" />
        </Head>
        
        
        <main className={styles.main}>
                 
          <h1 className={styles.title}>
            <a> More Interesting Stuff </a>
          </h1>

          <div className={styles.grid}>
          <a href="/Businesses" className={styles.card}>
            <h2>My Businesses &rarr;</h2>
            <p></p>
          </a>

          <a href="construction" className={styles.card}>
            <h2>SpaceX Launches &rarr;</h2>
            <p></p>
          </a>

          <a
            href="construction"
            className={styles.card}
          >
            <h2>Astronomy &rarr;</h2>
            <p></p>
          </a>

          <a
            href="/Web_Development"
            className={styles.card}
          >
            <h2>Web Development &rarr;</h2>
            <p></p>
          </a>

          <a href="/construction" className={styles.card}>
            <h2>A Dog's Guide &rarr;</h2>
            <Text fontWeight='thin' fontSize='small' fontStyle='normal'> Do you want to or already own a dog? Click this guide to find out more </Text>
          </a>
        </div>
        </main> 
      </div>
    )
}