import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {background, Code, flexbox, Image, Text, Button, Stat, StatNumber, Alert,
  AlertIcon,
  AlertTitle,
  AlertDescription, Wrap, WrapItem, Container, Grid, GridItem, useDisclosure, Modal,
  ModalOverlay,
  ModalContent,
  ModalHeader,
  ModalFooter,
  ModalBody,
  ModalCloseButton,} from '@chakra-ui/react'
import { PhoneIcon, CloseButton, ExternalLinkIcon } from '@chakra-ui/icons'
import { fromImageTOUrl, API_URL } from '../Components/Utils/urls'
import NextLink from 'next/link'
import Link from 'next/link'


export default function Home() {
  const { isOpen, onOpen, onClose } = useDisclosure()
   return (
    <div >
      <Head>
        <title>Josh Silva | Photography</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Josh_Logo_White.png" />
        <script data-ad-client="ca-pub-1604087287433448" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
      </Head>
      
      <main className={styles.main}>    
        <h1 className={styles.title}>
          <a href="https://www.instagram.com/j_daphotophile/" fontWeight="extrabold">JDaPhotophile</a>
        </h1>
        
        <Text className={styles.description} fontWeight='thin'>
          Welcome to my Photography Gallery
        </Text>
        
        <Grid templateColumns="repeat(5, 1fr)" templateRows="repeat(4, 1fr)" >
        {products.map(product => (
            <GridItem 
              boxShadow="base"
              rounded="10px"
              overflow="hidden"
              bg="white"
              boxShadow= "dark-lg" 
              margin="2"
            >
              <Image src={fromImageTOUrl(product.image)} height={200} width={250} onClick={onOpen} />

            </GridItem>
        ))}
        </Grid>
        
        <flexbox align="center">
          <Text>Like What you see? Click below to head over to my Store to pick one for that fabulous wall of yours</Text>
          <NextLink href="/Store">
            <Button > Store &nbsp;<ExternalLinkIcon/> </Button> 
          </NextLink>
          
        </flexbox>     
      </main>      
    </div>
  )
}

export async function getStaticProps() {
  //Fetch the products
  const product_res = await fetch(`${API_URL}/products/`)
  const products = await product_res.json()

  //Return the products as props
  return {
    props: {
      products
    }
  }
}
