import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import { Code } from '@chakra-ui/react'

export default function Web_Development() {
  return (
    <div className={styles.container}>
      
      <Head>
        <title>Josh Silva | Web Development</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Josh_Logo_White.png" />
      </Head>
      
      
      <main className={styles.main}>       
        <h1 className={styles.title}>
          <a href="https://www.instagram.com/j_damusicophile/">Web Development</a>
        </h1>

        <p className={styles.description}>
          Learn how this website was made, using: {' '}
          <Code className={styles.code}>-Next.js- -Chakra UI- -Vercel- -Apollo Client- -Sass- -Framer motion- </Code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          

          <a
            href="https://chakra-ui.com/docs/getting-started"
            className={styles.card}
          >
            <h2>Chackra UI &rarr;</h2>
            <p>
              Learn how to make beautiful websites, with amazing UI using Chackra UI.
            </p>
          </a>

          <a
            href="https://www.framer.com/docs/"
            className={styles.card}
          >
            <h2>Framer motion &rarr;</h2>
            <p>
              Learn how to make beautiful websites, with amazing animations using Framer motion.
            </p>
          </a>

          <a
            href="https://sass-lang.com/documentation"
            className={styles.card}
          >
            <h2>Sass &rarr;</h2>
            <p>
              Learn how to add amazing styling to your website using Sass.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>
    </div>
  )
}
